= Евгений Замрий
:hide-uri-scheme:
:icons: font
:stylesheet: ezamriy-cv.css
:stylesdir: ../theme
:nofooter:

[.contacts.text-center]
icon:envelope[] mailto:eugene@zamriy.ru[]
| icon:telegram[] https://t.me/ezamriy[@ezamriy,window=_blank]
| icon:github[] https://github.com/ezamriy[window=_blank]
| icon:globe[] https://zamriy.info[window=_blank]
| icon:map-pin[] Калуга, Россия

== О себе

Архитектор операционных систем на базе GNU/Linux. Специализируюсь на
автоматизации процессов разработки и сопровождения основанных на RPM
дистрибутивов, а также на создании системного и прикладного программного
обеспечения. Имею более десяти лет опыта управления проектами и распределёнными
командами в российских и международных ИТ-компаниях.

Принимал участие и сопровождал различные проекты с открытым исходным кодом,
понимаю, как взаимодействовать с сообществом.

== Профессиональные навыки

* *Разработка ПО:*
** Языки программирования: Python, Bash, Rust, Go, JavaScript (Vue.js).
** СУБД: PostgreSQL, MongoDB, InfluxDB, SQLite.
** Техническая документация, DocOps: AsciiDoc, Antora, Markdown, MkDocs, mdBook,
   Sphinx, Mermaid, Svgbob, OpenAPI.
** DevOps: Ansible, Terraform, Testinfra, Puppet, Serverspec.
** CI/CD и тестирование: Git, Jenkins, openQA, Packer, Gitea, Ansible Molecule,
   GitHub Actions, Test Kitchen.
** Контейнеризация: Docker, Podman.
** Виртуализация: QEMU/KVM, Proxmox, VirtualBox, VMWare.
** Облачные платформы: Yandex Cloud, AWS, Azure, OpenStack, Equinix Metal.
* *Операционные системы:*
** GNU/Linux (RHEL/Fedora, Debian/Ubuntu, openSUSE) - сборка дистрибутивов (на
   основе RPM), разработка ПО, системное администрирование, написание скриптов
   на Bash, Python и т.п. Использую GNU/Linux с 1997 года, разрабатываю
   различные дистрибутивы с 2012.
** Microsoft Windows, macOS - продвинутый пользователь.
* *Управление командами и проектами:* 14 лет опыта, Agile (Scrum, Kanban),
  Waterfall, стратегическое планирование, дорожные карты, технические
  спецификации, управление рисками и ресурсами, работа с распределёнными
  командами и т.п.

<<<

== Опыт работы

[.header-table, cols="~,>30", width="100%", grid="none", frame="none"]
|===
s| ООО "НЦПР" (ГК Softline), https://msvsphere-os.ru[window=_blank]
s| [.header-date]#дек 2022 - н.в.#
2+s| Главный архитектор ОС МСВСфера
|===

ОС МСВСфера - операционная система общего назначения, совместимая с
семейством Enterprise Linux (RHEL, Oracle Linux, AlmaLinux OS и т.д.). От
исходного дистрибутива продукт отличается адаптацией для рабочих станций,
множеством доработанных и разработанных с нуля системных и прикладных
компонентов, поддержкой российской криптографии (шифрование, туннели и пароли
по ГОСТ), совместимостью с процессорами Байкал-М, наличием отдельной редакции
для хостинг-провайдеров и сертификата ФСТЭК.

* Участвовал в формировании технического видения, дорожной карты развития ОС,
  риск-менеджменте и других активностях по управлению проектом.
* Сформировал и возглавил команду разработки и сопровождения проекта (27
  человек).
* Создавал спецификации и технические задания по разработке ОС и её компонентов.
* Развернул начальную инфраструктуру проекта в соответствии с принципами IaC.
* Разработал различные расширения сборочной системы Koji для автоматизации
  рутинных процессов.
* Разработал фреймворк для верификации собранных RPM пакетов и модулей.
* Внедрил в CI/CD конвейер проекта openQA для тестирования графических
  компонентов дистрибутива.
* Участвовал в создании руководства пользователя и администратора операционной
  системы.
* Модифицировал Docker, Libvirt и другие системные компоненты для соответствия
  требованиям ФСТЭК России, участвовал в подготовке документации, необходимой
  для сертификации.
* Выступал на профильных конференциях (OS Day, Хостобзор) и принимал участие в
различных корпоративных мероприятиях для продвижения продукта.

*Стек технологий:* Python, RPM, Koji, Jenkins, openQA, Ansible, Terraform,
Yandex Cloud, Proxmox, Bash, Rust, Go, PostgreSQL и т.п.

'''

[.header-table, cols="~,>30", width="100%", grid="none", frame="none"]
|===
s| AlmaLinux OS, https://almalinux.org[window=_blank]
s| [.header-date]#янв 2021 - ноя 2022#
2+s| Ведущий разработчик, менеджер проекта
|===

AlmaLinux OS - это дистрибутив GNU/Linux с открытым исходным кодом,
полностью совместимый с Red Hat Enterprise Linux.

* Координировал подготовку первых выпусков проекта.
* Развернул начальную инфраструктуру: git-хостинг, сборочную систему, Wiki,
  CI/CD и др.
* Выступал в роли менеджера проекта для сборочной системы дистрибутива.
* Был членом правления AlmaLinux OS Foundation с апреля 2021 по июль 2022 года.
* Участвовал в онлайн-мероприятиях для популяризации дистрибутива: прямой эфир
  запуска, конференции CentOS Dojo и Fedora Nest, AMA на Reddit, подкасты на
  русском и английском языках.
* Отвечал за сборку и сопровождение образов для систем виртуализации и
  контейнеризации. Взаимодействовал с ключевыми партнёрами и спонсорами проекта
  в целях предоставления оптимизированных образов для их платформ: Microsoft
  Azure, Amazon AWS и Equinix Metal.
* Добавил поддержку дистрибутива в проекты LXC и Docker Official Images.
* Автор и сопровождающий следующих проектов:
** https://github.com/AlmaLinux/cloud-images[window=_blank] - инструменты для
   сборки образов AlmaLinux OS под различные облачные платформы.
** https://github.com/AlmaLinux/docker-images[window=_blank] - инструменты для
   сборки образов контейнеров.
** https://github.com/AlmaLinux/almalinux-deploy[window=_blank] - утилита для
   миграции с других дистрибутивов, основанных на RHEL, на AlmaLinux OS.
** https://github.com/AlmaLinux/almalinux-witness[window=_blank] - система сбора
   и визуализации статистики о популярности дистрибутива.

*Достигнутые результаты:*

* Более 2 миллионов инсталляций, в том числе на 9 суперкомпьютерах из списка
  Top500, используется в качестве основной системы в
  https://linux.web.cern.ch/almalinux/[CERN,window=_blank] и Fermilab.
* Около 400 зеркал по всему миру, 4 поддерживаемых архитектуры (x86_64, aarch64,
  ppc64le, s390x).
* Спонсоры проекта: Amazon AWS, Microsoft Azure, Meta, AMD, Arm и др.
* От анонса до выпуска публичной бета версии прошло 54 дня, стабильная версия
  была выпущена за полтора месяца, обновления безопасности выпускаются в течение
  одного бизнес дня.

*Стек технологий:* Python, RPM, Docker, Podman, AWS, Azure, Packer, Ansible,
Terraform, Bash.

'''

[.header-table, cols="~,>30", width="100%", grid="none", frame="none"]
|===
s| Cloud Linux Inc., https://cloudlinux.com[window=_blank]
s| [.header-date]#янв 2021 - ноя 2022#
2+s| Директор по управлению релизами
|===

Cloud Linux Inc. - полностью удалённая международная технологическая компания,
разработавшая ряд уникальных решений для веб-хостинга. Флагманский продукт —
операционная система CloudLinux, коммерческий дистрибутив GNU/Linux,
оптимизированный под нужды провайдеров shared-хостинга.

* Отвечал за процессы, связанные со сборкой, верификацией и доставкой RPM и Deb
  пакетов разрабатываемого компанией ПО.
* Руководил командами разработки, отвечающими за:
** выпуск новых версий ОС CloudLinux и её сопровождение.
** сборку образов для различных платформ виртуализации (как для внутреннего
   CI/CD, так и для публичного использования).
** развитие корпоративной сборочной и CI/CD системы, автоматизацию рутинных
   задач.
* Отвечал за стратегическое планирование, управление ресурсами и рисками на
  уровне департамента.
* Выступал в роли технического консультанта проекта TuxCare Extended Lifecycle
  Support, цель которого — предоставление обновлений безопасности для устаревших
  дистрибутивов GNU/Linux (например, CentOS 6).

'''

[.header-table, cols="~,>30", width="100%", grid="none", frame="none"]
|===
s| Cloud Linux Inc., https://cloudlinux.com[window=_blank]
s| [.header-date]#ноя 2013 - дек 2020#
2+s| Архитектор, менеджер проектов
|===

Выступал в роли архитектора и руководителя проекта сборочной системы для
операционной системы CloudLinux и других продуктов компании. Основная цель
проекта - предоставление унифицированного решения для сборки, тестирования,
подписи и выпуска пакетов для нескольких дистрибутивов GNU/Linux
(CentOS/CloudLinux, Debian, Ubuntu).

* Управлял несколькими полностью удалёнными командами разработки.
* Реализовал ключевые компоненты системы: протоколы межкомпонентного
  взаимодействия на базе ZeroMQ, планировщик/балансировщик сборок, сервер
  публичного API и др.
* Разработал систему мониторинга релизов, отслеживающую появление новых версий
  ПО в git-репозиториях, на официальных сайтах и автоматически собирающую
  RPM-пакеты для них.
* Оказывал команде поддержку в задачах системного администрирования и DevOps.

Был архитектором и релиз-менеджером операционной системы CloudLinux с 2014 по
2019 год:

* Автоматизировал процессы сборки и верификации новых версий дистрибутива,
сократив время выпуска с 1,5 месяцев до 1–2 недель.
* Автоматизировал рутинные задачи по сопровождению: дебрендирование пакетов,
  сборка и тестирование обновлений.
* Задокументировал процессы сопровождения дистрибутива и обучил команду их
  выполнению.
* Руководил разработкой продуктов alt-php, alt-python, alt-ruby и alt-nodejs,
  предназначенных для предоставления альтернативных версий популярных языков
  программирования в ОС CloudLinux.
* Оказывал инженерам поддержки уровня L3 помощь в диагностике и решении сложных
  инцидентов (поддержка уровня L4).
* Взаимодействовал с партнёрами компании (cPanel, Plesk и др.) для улучшения
  совместимости и интеграции продуктов.

*Стек технологий:* Python, Bash, MongoDB, JavaScript, Jenkins, RPM, Mock,
ZeroMQ, Jira.

'''

[.header-table, cols="~,>30", width="100%", grid="none", frame="none"]
|===
s| Cloud Linux Inc., https://cloudlinux.com[window=_blank]
s| [.header-date]#авг 2012 - ноя 2013#
2+s| Ведущий разработчик
|===

Разработал MVP версию сборочной системы для операционной системы CloudLinux.
Целью была автоматизация рутинных процессов сборки и сопровождения дистрибутива:
сборки, тестирования, подписывания и выпуска RPM пакетов.

* Сформировал список требований и провёл исследование существующих решений:
  Koji, openSUSE Build Service, Jenkins и т.д.
* Подготовил описание архитектуры и реализовал функциональный прототип системы.
* Сформировал и возглавил команду из 3 разработчиков для работы над проектом.
* Осуществил перевод процесса сборки ОС CloudLinux со сборочной системы Koji на
  разрабатываемую систему.
* Выполнял функции ментора для разработчиков.
* Участвовал в подборе персонала, проводил технические собеседования.

*Стек технологий:* Python, Bash, MongoDB, JavaScript, RPM, Mock.

'''

[.header-table, cols="~,>30", width="100%", grid="none", frame="none"]
|===
s| Независимый разработчик
s| [.header-date]#июл 2009 - авг 2012#
|===

Проектирование и разработка различного ПО для SEO, веб-автоматизации и анализа
данных.

*Стек технологий:* Python, PostgreSQL, MongoDB, JavaScript (Ext JS), Scala,
HtmlUnit, Selenium.

'''

[.header-table, cols="~,>30", width="100%", grid="none", frame="none"]
|===
s| ОАО "ДОПАС"
s| [.header-date]#ноя 2004 - окт 2010#
2+s| Инженер-программист
|===

Предприятие ОАО "ДОПАС" (Донецкое Областное Предприятие Автобусных Станций)
являлось оператором сети автовокзалов Донецкой области Украины.

* Спроектировал и разработал финансово-аналитическую систему для автобусных
  станций. Основные функции:
** Обработка информации, поступающей с автовокзалов, генерация отчётов, экспорт
   данных в ПО "Акцент" и т.п.
** Анализ и прогнозирование пассажиропотока.
** Автоматизированный поиск нарушений в работе персонала автобусных станций.
** Интеграция с автоматизированной системой
   http://bus.com.ua/REC_AS.htm[Автовокзал,window=_blank].
* Разработал и внедрил систему автоматизации документооборота с пассажирскими
  перевозчиками.
* Участвовал во внедрении автоматизированной системы управления автовокзалами.

*Достигнутые результаты:*

* Выполнена цифровизация предприятия: переход от ручного заполнения бумажных
  отчётов и ведомостей к автоматической генерации электронных документов, что
  значительно повысило точность данных и ускорило внутренние процессы.
* На автовокзалах предприятия стали доступны услуги предварительного
  бронирования и продажи билетов, в том числе и дистанционно. Работа касс и
  диспетчерской службы значительно ускорилась.

*Стек технологий:* Perl, CGI, Python, PyGTK, MySQL, MUMPS.

== Образование

Донецкий институт предпринимательства, специальность - менеджмент организаций,
2005 - 2011.

== Рекомендации

- *Николай Анохин* - технический директор Инферит, ГК Softline
- *Мурад Мирзоев* - директор по развитию бизнеса, ГК Softline
- *Андрей Лукошко* - архитектор, AlmaLinux OS
- *Jack Aboutboul* - менеджер по работе с сообществом, член правления,
  AlmaLinux OS
- *Игорь Селецкий* - CEO, CloudLinux Inc.

== Знание языков

* *Английский* - продвинутый (C1)
* *Испанский* - средний (B1)
* *Русский* - родной
